import 'package:aksara_sunda/utils/materi.dart';

class MateriRepository {
  List<Materi> getMateriList() {
    return [
      Materi(
        judul:
            'History of Script Sundanese in the land of Sunda From Time to Time | (Sejarah Aksara Sunda Kaganga)',
        deskripsi1:
            'Assalamualaikum warahmatullahi wabarakatuh… Sampurasun… (Salam Budaya) Kali ini kita akan membahas tentang penggunaan aksara di Jawa Barat atau di wilayah Tatar Sunda khususnya aksara Sunda kaganga. Catatan sejarah aksara kaganga sunda telah digunakan sejak abad ke 14 masehi, salah satu buktinya adalah prasasti kawali atau prasasti astana gede yang dibuat sebagai peringatan kebesaran Prabu Niskala Wastu Kencana, seorang raja Sunda Galuh yang beribu kota adalah Kawali Ciamis pada tahun 1371 SM hingga 1475 SM (*Maaf benar mengatakannya) Selain pada prasasti Kawali, aksara Sunda juga digunakan pada prasasti Kebantenan yang dibuat pada abad ke-15 Masehi. disini tidak ada catatan sejarah yang pasti kapan lahirnya aksara Sunda, yang jelas sebelum abad ke 14, naskah dan prasasti lontar selalu menggunakan aksara Pallawa dan Jawa kuno, bahasa yang digunakan adalah bahasa Sansekerta dan Jawa kuno misalnya Prasasti Tugu pada abad ke 4. abad dan prasasti Sanghyang Tapak pada abad ke-11 M.',
        deskripsi2:
            'Naskah Sunda Kuno yang menggunakan aksara dan bahasa Sunda kuno antara lain naskah Carita Parahiangan, naskah Bujangga Manik, dan naskah Sewaka Dharma yang ketiganya ditulis pada abad ke-15 hingga abad ke-16. IKLAN. Naskah lain yang menggunakan aksara dan bahasa Sunda kuno adalah Naskah Sanghyang Siksa Kandang Karesian yang ditulis pada tahun 16 M dan Naskah Amanat Galunggung. Naskah Amanat Galunggung atau Naskah Kabuyutan Ciburuy diperkirakan lebih tua dibandingkan dengan Naskah Carita Parahyangan.Naskah Sunda kuno pada umumnya memuat ajaran tentang norma-norma kehidupan dan ditulis oleh para wiku di Mandala atau “kabuyutan”.',
        deskripsi3:
            'Sedangkan Situ Mandala atau Kabuyutan sendiri merupakan tempat pertapaan yang umumnya terletak di lereng atau kaki pegunungan seperti Gunung Galunggung, Gunung Cikuray, Gunung Wayang dan Gunung Jayagiri Pegon Arab antara lain kitab Waruga Jagat dari Sumedang dan naskah Pancakaki dari Karuhun Kabeh terbitan Ciamis, baik ditulis pada abad ke 18 Masehi maupun menggunakan bahasa Jawa. Setelah wilayah Priangan (Jawa Barat Atau Pasundan) dikuasai Kerajaan Mataram Islam, diperkenalkanlah aksara Jawa yang lebih dikenal dengan nama Hanacaraka atau Cacarakan. Salah satu aksara yang menggunakan aksara Jawa adalah Naskah Babad Pakuan dan Naskah Babad Pajajaran yang ditulis pada abad ke-19 Masehi. Sedangkan aksara Latin mulai digunakan setelah kedatangan bangsa Belanda ke Batavia. Setelah beberapa abad tenggelam, pada tahun 1990-an aksara Sunda diperkenalkan kembali namun aksara Sunda yang kita kenal sekarang merupakan hasil modifikasi para filolog berdasarkan teks-teks yang menggunakan aksara Sunda kuno. terdapat juga beberapa huruf yang ditambahkan seperti “Fa, Va, Qa, Xa, Za, Kha, dan Sya” Demi keseragaman, maka disusunlah aksara Sunda Lulugu atau aksara Sunda baku dan berdasarkan Peraturan Daerah Jawa Barat nomor 6 tahun 1996, selain bahasa dan sastra Sunda, aksara Sunda juga wajib diajarkan di sekolah-sekolah di wilayah Jawa Barat.',
        deskripsi4:
            'Oleh karena itu, Aksara Kaganga Sunda yang kita kenal sekarang ini mempunyai 7 aksara bunyi atau huruf vokal, 23 aksara ngalagena atau konsonan, dan 13 rarangken atau imbuhan, 10 angka dan beberapa tanda baca Aksara suara atau aksara vokal merupakan aksara yang mempunyai bunyi vokal yang terdiri dari “a, i, u, e, o, e\' & eu” Sedangkan aksara Ngalagena terdiri atas “ka, ga, nga, ca, ja, nya, ta, da, na, pa, ba, ma, ya, ra, la dan wa, sa, ha”. Kemudian ditambah huruf baru yaitu “Fa, Va, Qa, Xa, Za, Kha, dan Sya” kemudian ditambah huruf baru yaitu “Fa, Va, Qa, Xa, Za, Kha, dan Sya” Dan itulah pembahasan terkait penggunaan karakter wilayah jawa barat atau wilayah sunda dari waktu ke waktu Terima kasih sudah menonton.',
        link: 'https://www.youtube.com/watch?v=e34Aa_qBjt8',
        image: 'images/mengupas_sejarah.PNG',
      ),
      Materi(
        judul: 'SEJARAH AKSARA SUNDA...',
        deskripsi1:
            'Sampurasun! Hari ini kita akan belajar sejarah tentang aksara Sunda, aksara Sunda yang begitu penuh dengan makna. Aksara Sunda ini, menurut catatan sejarah, sudah dipakai oleh masyarakat Sunda sejak abad ke-14 sampai dengan abad ke-18. Hal itu dapat kita lihat di dalam prasasti yang ada di Astana Gede Kawali, yaitu di Ciamis, dan ada lagi prasasti Kebantenan yang ada di Bekasi. Masyarakat Sunda ini sudah lama menggunakan aksara Sunda.',
        deskripsi2:
            'Dek, hai! Hari ini, aksara Sunda dipakai untuk menuliskan bahasa keseharian mereka. Namun, setelah masuknya kolonial penjajahan, masyarakat Sunda dituntut untuk meninggalkan aksara Sunda ini. Padahal, aksara Sunda ini sebagai identitas kebudayaan orang Sunda. Dengan hal itu, mengakibatkan generasi selanjutnya tidak mengenal yang namanya aksara Sunda. Hal itu dipertegas dengan VOC yang membuat surat keputusan bahwa aksara di Jawa Barat adalah aksara Latin, aksara Arab, dan aksara Jawa, yang ditetapkan pada tanggal 3 November 1705. Hal itu didukung oleh penguasa Cirebon dengan menerbitkan surat keputusan pada tanggal 9 Februari 1706. Sejak saat itulah, aksara Sunda berabad-abad hilang dan terlupakan. Bahkan, generasi selanjutnya pun tidak mengetahui bahwa ada aksara Sunda di Jawa Barat, karena saking lamanya itu terlupakan dan terabaikan.',
        deskripsi3:
            'Setelah itu, Islam masuklah ke Jawa Barat, ya, ke Indonesia. Di situlah aksara Sunda semakin tergeser, digantikan dengan aksara Arab yang berdominasi tulis-menulis di wilayah Jawa Barat. Aksara Arab ini disebut Pegon. Tapi, tidak hanya aksara Arab yang mengikis aksara Sunda ini, tetapi pada zaman itu ada cara latihan yang masuk, yang diperkenalkan oleh orang Eropa yang dibawa oleh kolonial. Mereka masuk dan mengenalkan aksara Latin kepada masyarakat pada abad ke-17. Dari situlah, aksara Sunda semakin tergeser dan tergerus.',
        deskripsi4:
            'Sampai saat ini pun, sedikit sekali orang yang mengetahui tentang aksara Sunda ini. Aksara Sunda ini ada 32 aksara, tujuh di antaranya adalah aksara Swara atau huruf vokal. Jika di Jerman saat ini adalah a, i, u, e, o, di Sunda dulu ada yang namanya a, i, u, e, o, dan heu, heu. Itu hampir sama, sebenarnya. Sedangkan sisanya, 23 aksara, adalah aksara ngalagena atau konsonan. ',
        link: 'https://www.youtube.com/watch?v=WdfjRpWseKY&t=17s',
        image: 'images/sejarah_aksara_sunda.PNG',
      ),
      Materi(
        judul: 'ADAKAH YANG PEDULI AKSARA SUNDA BUHUN ???',
        deskripsi1:
            'Jadi, kalau menurut saya, kenapa orang tidak peduli lagi dengan aksara hai? Karena aksara daerah, khususnya aksara Sunda dan aksara Carakan, itu sudah tidak dianggap lagi relevan lah atau sudah kurang hai. Bisa difungsikan, contoh: piala hai. Ketika seseorang bisa nulis aksara Sunda, ketika seseorang bisa nulis aksara Carakan, itu maha bisa dipakai ngelamar gawe. Woah, padahal hai, padahal fungsi aksara itu keren. Anga rekam jejak, rekam ngerekam, akhir-akhir ngerekam segala sesuatu anu terjadi masa lampau. Contoh: air hai. Ketika buyut belum begitu hafal karena aksara Latin, maka beliau akan menulis pucat tarakan atau aksara Sunda. Nah, peninggalan buyutnya kan malam mama mah bisa dibaca kau anak-anak yang tidak pernah mempelajari aksara kita. Commode sampai kak mengenai filosofinya, karena on hap ketik di dipedar, khususnya aksara Carakan, aksara Sunda itu ayah filosofinya. Contoh: aksara Carakan kunaon susunan? Padahal di unicorn, unicorn itu cakar akan oke, karena termasuk karakan itu nih di unicorn genereh kg. Nah, tapi kenapa di masyarakat Jawa, masyarakat guna susunan anak jadi lain? Udah make kagak deh, tapi hanacaraka datasawala. Padhajayanya magabathanga hai. Scanning dibuka hai, hanacaraka. Hanacaraka itu ayah 22, gua sosobatan. Caraka itu persahabatan, karena itu sosobatan ayah dua sosok batak.',
        deskripsi2:
            'Padhajayanya sarua jagona maga bathanga, sarwana batangn atau sarwa meninggal. Buka line, udah lu dilatarbelakangi ku cerita Aji Saka ing Dewatacengkar, numutkeun dongeng bahwa lahir. Nah, ya iya, dongeng lahirna hanacaraka itu Aji Saka ketika Aji Saka ayeuna hai. Pengaruh Medang Kamulan merebut kekuasaan di Medang Kamulan, key Dewatacengkar. Makan maneh boga, pernah kawan-kawan datasawala. Heytea hanacarakanya. Semoga ponakawan dora gym sembada ketika ia berangkat ngaruh sehat. Arek-arek mengambil kekuasaan Medang Kamulan. Mosa urang mah di sini dora. Eh iya, sembada anu dibawakan ukur nora. Kunaon beut dora hai. Sembada kalahkan disimpan di vitamin nungguan pusaka.',
        deskripsi3:
            'Menjadi pertanyaan, ia rur cerita ramma. Orang bisa jiwanya di toko bu, tapi enggak. Jadi pertanyaan, saha atuh? Norak sangat sembada. Saha Aji Saka? Saha Dewatacengkar? Terjadi pertanyaan setiap dong rakyat itu mempunyai filosofi. Mempunyai filosofi guarin murah hai. Setiap disebut dewa, tak berarti majemuk lebih dari satu orang. Ya udah sampai, belum satu orang mah disebut lagi dewa-dewa adalah penguasa.',
        deskripsi4:
            'Akhir-akhir, amun dewata berarti penguasa-penguasa. Hai cengkar, itu harus binatang kartu tandus gersang. Karena dina bahasa Sunda, nu disebut tandus atau gersang teh itu hangar. Hai, hai, hai. Bahasa Sunda itu hangat. Lamun bahasa itu, nah itu cengkar berarti Dewatacengkar. Hardina penguasa-penguasa yang berhati tandus atau gersang. Ia berusaha atau Aji Saka tanahmas di Pulau Majeti. Majeti Aji berarti ilmu, Saka berarti sopo pihak anu kokoh kuat. Halo, mak yati, mak berarti induk. Yakin Nusajati melahirkan ar-rahim Nusajati dalam arti lokal. Hantu dora-dora dursila itu bohong gede, hatinya bohong gede atau licik gede. Kunaon pada saat eta nu dibawa teh dora? Karena nongkrong merebut kekuasaan pemerintahan. Lah menjadi barengan kulit, dibohongi tumor. Jadi insya hai asep yang amanah, maka maneh disimpan kita nungguan pusaka nu di akhir kemudiannya diputus. Gua Aji Saka suruh ngambil barang pusaka. Data akhirnya perebutan, perebusan wiji mempertahankan amanah no siji. Ngerasa jadi utusan, akhirnya meninggal dua anaknya. Lahirlah hanacaraka datasawala. Padhajayanya magabathanga.',
        link: 'https://www.youtube.com/watch?v=nCrnwJYhQiQ',
        image: 'images/aksara_sunda_buhun.PNG',
      ),
      Materi(
        judul: 'SUNDANOLOGI | JEJAK AJARAN BANGSA SUNDA DI DUNIA',
        deskripsi1:
            'Keberadaan ajaran Sunda yang masih tersisa hingga saat ini terekam dalam kebudayaan bangsa Barat Eropa. Ya, istilah "sundayana" dikenal menjadi "hari matahari," sedangkan di Nusantara kelak dikenal dengan sebutan "Suriah," yang berasal dari empat suku kata. Kita bedah lagi dari Sastra Jendra. Hai, ada sebuah huruf "sawah Raya" atau "Surya." Bangsa Nusantara memperingatinya dalam upacara surat atau kita mengenalnya dengan "Syuro," yang intinya bertujuan untuk mengungkapkan rasa terima kasih serta ungkapan rasa syukur atas kesuburan dan kemakmuran di negara dalam segala bentuk kehidupan, baik berupa makanan, udara, air, api, kehangatan, lalu tanah, dan lain sebagainya.',
        deskripsi2:
            'Nah, pengertian "Suryana" itu sendiri hakekatnya sama saja dengan "sundayana," sebab mengandung maksud dan makna yang hampir sama. Ada huruf "sak Wara Yana" atau ajaran ketunggalan-Nya, sinar matahari, atau mungkin sekarang kita mengenalnya dengan "hay lastro lobi" atau kesemestaan. Mungkin ya, maka arti "Suryana" itu adalah ajaran matahari yang sejati, energi matahari yang sejati. Yang di kemudian hari, bangsa Indonesia mengenal dan mengabadikannya dengan sebutan "Sang Surya" untuk pengganti istilah matahari. Eh, apa yang menyebabkan bangsa Indonesia pada saat ini menyebut Sang Surya itu sebagai matahari? Dari manakah gagasan istilah "mata" dan "hari" muncul? Kenapa masyarakat Jawa Barat menyebutnya sebagai "Panon"? Proyek itu, Er. Mengapa bisa terjadi kemiripan dengan yang ada juga di Mesir? Atau apa kaitannya dengan istilah Sunda itu sendiri? Nah, dalam catatan sejarah dunia hasil penelitian para ilmuwan Barat yang berkembang saat ini, disebutkan bahwa kebudayaan Mesir Kuno adalah peradaban yang tertua di Indonesia. Hal tersebut boleh jadi benar menurut sisi bukti fisik, namun perlu dipertanyakan pula dari siapa dan dari mana masyarakat Mesir Kuno itu mempelajari peradaban itu.',
        deskripsi3:
            'Apakah sisa peradaban atau nilai-nilai itu masih tersisa dan menampakkan dalam pola hidup keseharian pada masyarakat pewaris kebudayaan itu? Di Mesir juga perlu dipertanyakan, terdapat keanehan dan seolah terjadi pilih kasih terhadap jejak sejarah kebudayaan dunia. Para ilmuwan Barat sepertinya sedikit alergi untuk mengorek dan mengutak-atik kebudayaan suku Aztec, Inka, Maya, Amerika Latin. Padahal kebudayaan mereka tidak kalah tua dan tidak kalah hebatnya dibandingkan dengan kebudayaan Mesir Kuno di Timur Tengah. Mungkin secara politis, ya, apabila hal itu dilakukan sama dengan membongkar aib mereka. Nah, hal tersebut di atas tidak ada bedanya dengan yang terjadi di Nusantara Indonesia. Hingga saat ini, sejarah Nusantara seperti dengan sengaja ditimbun dan dibenamkan sedalam-dalamnya. Kisah sejarah terjauh yang dipahami oleh generasi muda Indonesia adalah cerita Kerajaan Sriwijaya dan Majapahit. Di belakang zaman itu, seolah-olah hanya kegelapan, atau kita mengenalnya primitif.',
        deskripsi4:
            'Ya, kembali lagi kita pada persoalan Sunda sebagai ajaran dari sebuah mempelajari energi matahari yang dianut oleh bangsa Galuh, yang telah mewarnai peradaban dunia. Sekilas digambarkan mengenai apa matahari yang kita kenal dengan "sundayana," lalu "Suryana." Di dalam kala idealnya, mereka menamai hari matahari atau dikenal dengan matahari itu "San" dan hari itu "day." Hari matahari atau Surya ada yang mengenalnya juga "San" atau "Sin" atau "than" atau "ingsun." Di kita ini ada juga yang "sanggup" atau "sound," begitu ya. Atau perubahan istilah itu yang berkaitan dengan Sunda. Sebetulnya sekilas gambaran tadi boleh jadi hanya bersifat "gathuk," katanya kata orang Indonesia yang mencocokkan gitu. Namun, mustahil jika kemiripan penanda sebutan dan objek itu terjadi dengan sendirinya tanpa sebab. Selain itu, terjadi pula kemiripan pada nilai-nilai yang bersifat prinsip. Jadi, pada saat kita menstigma kan tentang cocokologi tadi, harusnya fair juga kalau kita mendengarkan istilah "herdis" dalam bahasa Inggris. Itu asal kata "Ferdy," situ dari "Firdaus." Katanya ini er tatali bahasa tuh.',
        link: 'https://www.youtube.com/watch?v=4Q2qrZMzPdI',
        image: 'images/sundanologi.PNG',
      ),
      Materi(
        judul: 'BELAJAR AKSARA SUNDA DENGAN MUDAH',
        deskripsi1:
            'Aksara Sunda saat ini diajarkan di sekolah. Kebanyakan dari siswa biasanya ingin belajar aksara Sunda dengan mudah. Video ini merupakan pembelajaran aksara Sunda yang dikemas agar mudah dipahami oleh berbagai kalangan, termasuk siswa SD, SMP, SMA, atau umum. Pembelajaran ini tidak hanya mencakup cara menulis aksara Sunda, tetapi juga menjelaskan makna dan sejarah di balik setiap huruf. Dengan pendekatan yang interaktif dan menarik, diharapkan siswa dapat lebih cepat memahami dan menguasai aksara ini.',
        deskripsi2:
            'Selain itu, metode pengajaran yang digunakan dalam video ini mencakup latihan-latihan praktis yang dapat diikuti oleh para siswa. Dengan memberikan contoh-contoh nyata dan aplikasi aksara Sunda dalam kehidupan sehari-hari, siswa diharapkan dapat melihat relevansi dan pentingnya mempelajari aksara ini. Misalnya, mereka dapat belajar menulis nama mereka atau membuat kalimat sederhana dalam aksara Sunda. Hal ini akan meningkatkan minat dan motivasi siswa untuk terus belajar.',
        deskripsi3:
            'Video pembelajaran ini juga dilengkapi dengan visual yang menarik dan penjelasan yang jelas. Dengan menggunakan animasi dan grafik yang menarik, siswa akan lebih terlibat dan tidak merasa bosan saat belajar. Selain itu, penyampaian materi yang sederhana dan lugas akan membantu siswa dari berbagai usia untuk memahami konsep-konsep dasar aksara Sunda dengan lebih baik. Dengan cara ini, diharapkan pembelajaran aksara Sunda menjadi lebih menyenangkan dan tidak menakutkan bagi siswa.',
        deskripsi4:
            'Dengan adanya inisiatif seperti ini, diharapkan aksara Sunda dapat terus dilestarikan dan diperkenalkan kepada generasi muda. Melalui pembelajaran yang menyenangkan dan mudah diakses, siswa tidak hanya akan belajar tentang aksara Sunda, tetapi juga akan menghargai warisan budaya yang ada. Dengan demikian, mereka akan menjadi generasi yang lebih sadar akan pentingnya melestarikan dan meneruskan budaya lokal, termasuk aksara Sunda, kepada generasi berikutnya.',
        link: 'https://www.youtube.com/watch?v=0f9LolhrhYs&t=166s',
        image: 'images/belajar_aksara.PNG',
      ),

      // Tambahkan materi lainnya sesuai kebutuhan
    ];
  }
}
