import 'package:aksara_sunda/utils/materi.dart';

class MateriRepository {
  List<Materi> getMateriList() {
    return [
      Materi(
        judul:
            'History of Script Sundanese in the land of Sunda From Time to Time | (Sejarah Aksara Sunda Kaganga)',
        deskripsi1:
            'Assalamualaikum warahmatullahi wabarakatuh… Sampurasun… (Salam Budaya) Kali ini kita akan membahas tentang penggunaan aksara di Jawa Barat atau di wilayah Tatar Sunda khususnya aksara Sunda kaganga. Catatan sejarah aksara kaganga sunda telah digunakan sejak abad ke 14 masehi, salah satu buktinya adalah prasasti kawali atau prasasti astana gede yang dibuat sebagai peringatan kebesaran Prabu Niskala Wastu Kencana, seorang raja Sunda Galuh yang beribu kota adalah Kawali Ciamis pada tahun 1371 SM hingga 1475 SM (*Maaf benar mengatakannya) Selain pada prasasti Kawali, aksara Sunda juga digunakan pada prasasti Kebantenan yang dibuat pada abad ke-15 Masehi. disini tidak ada catatan sejarah yang pasti kapan lahirnya aksara Sunda, yang jelas sebelum abad ke 14, naskah dan prasasti lontar selalu menggunakan aksara Pallawa dan Jawa kuno, bahasa yang digunakan adalah bahasa Sansekerta dan Jawa kuno misalnya Prasasti Tugu pada abad ke 4. abad dan prasasti Sanghyang Tapak pada abad ke-11 M.',
        deskripsi2:
            'Naskah Sunda Kuno yang menggunakan aksara dan bahasa Sunda kuno antara lain naskah Carita Parahiangan, naskah Bujangga Manik, dan naskah Sewaka Dharma yang ketiganya ditulis pada abad ke-15 hingga abad ke-16. IKLAN. Naskah lain yang menggunakan aksara dan bahasa Sunda kuno adalah Naskah Sanghyang Siksa Kandang Karesian yang ditulis pada tahun 16 M dan Naskah Amanat Galunggung. Naskah Amanat Galunggung atau Naskah Kabuyutan Ciburuy diperkirakan lebih tua dibandingkan dengan Naskah Carita Parahyangan.Naskah Sunda kuno pada umumnya memuat ajaran tentang norma-norma kehidupan dan ditulis oleh para wiku di Mandala atau “kabuyutan”.',
        deskripsi3:
            'Sedangkan Situ Mandala atau Kabuyutan sendiri merupakan tempat pertapaan yang umumnya terletak di lereng atau kaki pegunungan seperti Gunung Galunggung, Gunung Cikuray, Gunung Wayang dan Gunung Jayagiri Pegon Arab antara lain kitab Waruga Jagat dari Sumedang dan naskah Pancakaki dari Karuhun Kabeh terbitan Ciamis, baik ditulis pada abad ke 18 Masehi maupun menggunakan bahasa Jawa. Setelah wilayah Priangan (Jawa Barat Atau Pasundan) dikuasai Kerajaan Mataram Islam, diperkenalkanlah aksara Jawa yang lebih dikenal dengan nama Hanacaraka atau Cacarakan. Salah satu aksara yang menggunakan aksara Jawa adalah Naskah Babad Pakuan dan Naskah Babad Pajajaran yang ditulis pada abad ke-19 Masehi. Sedangkan aksara Latin mulai digunakan setelah kedatangan bangsa Belanda ke Batavia. Setelah beberapa abad tenggelam, pada tahun 1990-an aksara Sunda diperkenalkan kembali namun aksara Sunda yang kita kenal sekarang merupakan hasil modifikasi para filolog berdasarkan teks-teks yang menggunakan aksara Sunda kuno. terdapat juga beberapa huruf yang ditambahkan seperti “Fa, Va, Qa, Xa, Za, Kha, dan Sya” Demi keseragaman, maka disusunlah aksara Sunda Lulugu atau aksara Sunda baku dan berdasarkan Peraturan Daerah Jawa Barat nomor 6 tahun 1996, selain bahasa dan sastra Sunda, aksara Sunda juga wajib diajarkan di sekolah-sekolah di wilayah Jawa Barat.',
        deskripsi4:
            'Oleh karena itu, Aksara Kaganga Sunda yang kita kenal sekarang ini mempunyai 7 aksara bunyi atau huruf vokal, 23 aksara ngalagena atau konsonan, dan 13 rarangken atau imbuhan, 10 angka dan beberapa tanda baca Aksara suara atau aksara vokal merupakan aksara yang mempunyai bunyi vokal yang terdiri dari “a, i, u, e, o, e\' & eu” Sedangkan aksara Ngalagena terdiri atas “ka, ga, nga, ca, ja, nya, ta, da, na, pa, ba, ma, ya, ra, la dan wa, sa, ha”. Kemudian ditambah huruf baru yaitu “Fa, Va, Qa, Xa, Za, Kha, dan Sya” kemudian ditambah huruf baru yaitu “Fa, Va, Qa, Xa, Za, Kha, dan Sya” Dan itulah pembahasan terkait penggunaan karakter wilayah jawa barat atau wilayah sunda dari waktu ke waktu Terima kasih sudah menonton.',
        link: 'https://www.youtube.com/watch?v=e34Aa_qBjt8',
        image: 'images/mengupas_sejarah.PNG',
      ),
      Materi(
        judul: 'SEJARAH AKSARA SUNDA...',
        deskripsi1:
            'Sampurasun! Hari ini kita akan belajar sejarah tentang aksara Sunda, aksara Sunda yang begitu penuh dengan makna. Aksara Sunda ini, menurut catatan sejarah, sudah dipakai oleh masyarakat Sunda sejak abad ke-14 sampai dengan abad ke-18. Hal itu dapat kita lihat di dalam prasasti yang ada di Astana Gede Kawali, yaitu di Ciamis, dan ada lagi prasasti Kebantenan yang ada di Bekasi. Masyarakat Sunda ini sudah lama menggunakan aksara Sunda.',
        deskripsi2:
            'Dek, hai! Hari ini, aksara Sunda dipakai untuk menuliskan bahasa keseharian mereka. Namun, setelah masuknya kolonial penjajahan, masyarakat Sunda dituntut untuk meninggalkan aksara Sunda ini. Padahal, aksara Sunda ini sebagai identitas kebudayaan orang Sunda. Dengan hal itu, mengakibatkan generasi selanjutnya tidak mengenal yang namanya aksara Sunda. Hal itu dipertegas dengan VOC yang membuat surat keputusan bahwa aksara di Jawa Barat adalah aksara Latin, aksara Arab, dan aksara Jawa, yang ditetapkan pada tanggal 3 November 1705. Hal itu didukung oleh penguasa Cirebon dengan menerbitkan surat keputusan pada tanggal 9 Februari 1706. Sejak saat itulah, aksara Sunda berabad-abad hilang dan terlupakan. Bahkan, generasi selanjutnya pun tidak mengetahui bahwa ada aksara Sunda di Jawa Barat, karena saking lamanya itu terlupakan dan terabaikan.',
        deskripsi3:
            'Setelah itu, Islam masuklah ke Jawa Barat, ya, ke Indonesia. Di situlah aksara Sunda semakin tergeser, digantikan dengan aksara Arab yang berdominasi tulis-menulis di wilayah Jawa Barat. Aksara Arab ini disebut Pegon. Tapi, tidak hanya aksara Arab yang mengikis aksara Sunda ini, tetapi pada zaman itu ada cara latihan yang masuk, yang diperkenalkan oleh orang Eropa yang dibawa oleh kolonial. Mereka masuk dan mengenalkan aksara Latin kepada masyarakat pada abad ke-17. Dari situlah, aksara Sunda semakin tergeser dan tergerus.',
        deskripsi4:
            'Sampai saat ini pun, sedikit sekali orang yang mengetahui tentang aksara Sunda ini. Aksara Sunda ini ada 32 aksara, tujuh di antaranya adalah aksara Swara atau huruf vokal. Jika di Jerman saat ini adalah a, i, u, e, o, di Sunda dulu ada yang namanya a, i, u, e, o, dan heu, heu. Itu hampir sama, sebenarnya. Sedangkan sisanya, 23 aksara, adalah aksara ngalagena atau konsonan. ',
        link: 'https://www.youtube.com/watch?v=WdfjRpWseKY&t=17s',
        image: 'images/sejarah_aksara_sunda.PNG',
      ),
      Materi(
        judul: 'ADAKAH YANG PEDULI AKSARA SUNDA BUHUN ???',
        deskripsi1:
            'Jadi, kalau menurut saya, kenapa orang tidak peduli lagi dengan aksara hai? Karena aksara daerah, khususnya aksara Sunda dan aksara Carakan, itu sudah tidak dianggap lagi relevan lah atau sudah kurang hai. Bisa difungsikan, contoh: piala hai. Ketika seseorang bisa nulis aksara Sunda, ketika seseorang bisa nulis aksara Carakan, itu maha bisa dipakai ngelamar gawe. Woah, padahal hai, padahal fungsi aksara itu keren. Anga rekam jejak, rekam ngerekam, akhir-akhir ngerekam segala sesuatu anu terjadi masa lampau. Contoh: air hai. Ketika buyut belum begitu hafal karena aksara Latin, maka beliau akan menulis pucat tarakan atau aksara Sunda. Nah, peninggalan buyutnya kan malam mama mah bisa dibaca kau anak-anak yang tidak pernah mempelajari aksara kita. Commode sampai kak mengenai filosofinya, karena on hap ketik di dipedar, khususnya aksara Carakan, aksara Sunda itu ayah filosofinya. Contoh: aksara Carakan kunaon susunan? Padahal di unicorn, unicorn itu cakar akan oke, karena termasuk karakan itu nih di unicorn genereh kg. Nah, tapi kenapa di masyarakat Jawa, masyarakat guna susunan anak jadi lain? Udah make kagak deh, tapi hanacaraka datasawala. Padhajayanya magabathanga hai. Scanning dibuka hai, hanacaraka. Hanacaraka itu ayah 22, gua sosobatan. Caraka itu persahabatan, karena itu sosobatan ayah dua sosok batak.',
        deskripsi2:
            'Padhajayanya sarua jagona maga bathanga, sarwana batangn atau sarwa meninggal. Buka line, udah lu dilatarbelakangi ku cerita Aji Saka ing Dewatacengkar, numutkeun dongeng bahwa lahir. Nah, ya iya, dongeng lahirna hanacaraka itu Aji Saka ketika Aji Saka ayeuna hai. Pengaruh Medang Kamulan merebut kekuasaan di Medang Kamulan, key Dewatacengkar. Makan maneh boga, pernah kawan-kawan datasawala. Heytea hanacarakanya. Semoga ponakawan dora gym sembada ketika ia berangkat ngaruh sehat. Arek-arek mengambil kekuasaan Medang Kamulan. Mosa urang mah di sini dora. Eh iya, sembada anu dibawakan ukur nora. Kunaon beut dora hai. Sembada kalahkan disimpan di vitamin nungguan pusaka.',
        deskripsi3:
            'Menjadi pertanyaan, ia rur cerita ramma. Orang bisa jiwanya di toko bu, tapi enggak. Jadi pertanyaan, saha atuh? Norak sangat sembada. Saha Aji Saka? Saha Dewatacengkar? Terjadi pertanyaan setiap dong rakyat itu mempunyai filosofi. Mempunyai filosofi guarin murah hai. Setiap disebut dewa, tak berarti majemuk lebih dari satu orang. Ya udah sampai, belum satu orang mah disebut lagi dewa-dewa adalah penguasa.',
        deskripsi4:
            'Akhir-akhir, amun dewata berarti penguasa-penguasa. Hai cengkar, itu harus binatang kartu tandus gersang. Karena dina bahasa Sunda, nu disebut tandus atau gersang teh itu hangar. Hai, hai, hai. Bahasa Sunda itu hangat. Lamun bahasa itu, nah itu cengkar berarti Dewatacengkar. Hardina penguasa-penguasa yang berhati tandus atau gersang. Ia berusaha atau Aji Saka tanahmas di Pulau Majeti. Majeti Aji berarti ilmu, Saka berarti sopo pihak anu kokoh kuat. Halo, mak yati, mak berarti induk. Yakin Nusajati melahirkan ar-rahim Nusajati dalam arti lokal. Hantu dora-dora dursila itu bohong gede, hatinya bohong gede atau licik gede. Kunaon pada saat eta nu dibawa teh dora? Karena nongkrong merebut kekuasaan pemerintahan. Lah menjadi barengan kulit, dibohongi tumor. Jadi insya hai asep yang amanah, maka maneh disimpan kita nungguan pusaka nu di akhir kemudiannya diputus. Gua Aji Saka suruh ngambil barang pusaka. Data akhirnya perebutan, perebusan wiji mempertahankan amanah no siji. Ngerasa jadi utusan, akhirnya meninggal dua anaknya. Lahirlah hanacaraka datasawala. Padhajayanya magabathanga.',
        link: 'https://www.youtube.com/watch?v=nCrnwJYhQiQ',
        image: 'images/aksara_sunda_buhun.PNG',
      ),
      Materi(
        judul: 'SUNDANOLOGI | JEJAK AJARAN BANGSA SUNDA DI DUNIA',
        deskripsi1:
            'Keberadaan ajaran Sunda yang masih tersisa hingga saat ini terekam dalam kebudayaan bangsa Barat Eropa. Ya, istilah "sundayana" dikenal menjadi "hari matahari," sedangkan di Nusantara kelak dikenal dengan sebutan "Suriah," yang berasal dari empat suku kata. Kita bedah lagi dari Sastra Jendra. Hai, ada sebuah huruf "sawah Raya" atau "Surya." Bangsa Nusantara memperingatinya dalam upacara surat atau kita mengenalnya dengan "Syuro," yang intinya bertujuan untuk mengungkapkan rasa terima kasih serta ungkapan rasa syukur atas kesuburan dan kemakmuran di negara dalam segala bentuk kehidupan, baik berupa makanan, udara, air, api, kehangatan, lalu tanah, dan lain sebagainya.',
        deskripsi2:
            'Nah, pengertian "Suryana" itu sendiri hakekatnya sama saja dengan "sundayana," sebab mengandung maksud dan makna yang hampir sama. Ada huruf "sak Wara Yana" atau ajaran ketunggalan-Nya, sinar matahari, atau mungkin sekarang kita mengenalnya dengan "hay lastro lobi" atau kesemestaan. Mungkin ya, maka arti "Suryana" itu adalah ajaran matahari yang sejati, energi matahari yang sejati. Yang di kemudian hari, bangsa Indonesia mengenal dan mengabadikannya dengan sebutan "Sang Surya" untuk pengganti istilah matahari. Eh, apa yang menyebabkan bangsa Indonesia pada saat ini menyebut Sang Surya itu sebagai matahari? Dari manakah gagasan istilah "mata" dan "hari" muncul? Kenapa masyarakat Jawa Barat menyebutnya sebagai "Panon"? Proyek itu, Er. Mengapa bisa terjadi kemiripan dengan yang ada juga di Mesir? Atau apa kaitannya dengan istilah Sunda itu sendiri? Nah, dalam catatan sejarah dunia hasil penelitian para ilmuwan Barat yang berkembang saat ini, disebutkan bahwa kebudayaan Mesir Kuno adalah peradaban yang tertua di Indonesia. Hal tersebut boleh jadi benar menurut sisi bukti fisik, namun perlu dipertanyakan pula dari siapa dan dari mana masyarakat Mesir Kuno itu mempelajari peradaban itu.',
        deskripsi3:
            'Apakah sisa peradaban atau nilai-nilai itu masih tersisa dan menampakkan dalam pola hidup keseharian pada masyarakat pewaris kebudayaan itu? Di Mesir juga perlu dipertanyakan, terdapat keanehan dan seolah terjadi pilih kasih terhadap jejak sejarah kebudayaan dunia. Para ilmuwan Barat sepertinya sedikit alergi untuk mengorek dan mengutak-atik kebudayaan suku Aztec, Inka, Maya, Amerika Latin. Padahal kebudayaan mereka tidak kalah tua dan tidak kalah hebatnya dibandingkan dengan kebudayaan Mesir Kuno di Timur Tengah. Mungkin secara politis, ya, apabila hal itu dilakukan sama dengan membongkar aib mereka. Nah, hal tersebut di atas tidak ada bedanya dengan yang terjadi di Nusantara Indonesia. Hingga saat ini, sejarah Nusantara seperti dengan sengaja ditimbun dan dibenamkan sedalam-dalamnya. Kisah sejarah terjauh yang dipahami oleh generasi muda Indonesia adalah cerita Kerajaan Sriwijaya dan Majapahit. Di belakang zaman itu, seolah-olah hanya kegelapan, atau kita mengenalnya primitif.',
        deskripsi4:
            'Ya, kembali lagi kita pada persoalan Sunda sebagai ajaran dari sebuah mempelajari energi matahari yang dianut oleh bangsa Galuh, yang telah mewarnai peradaban dunia. Sekilas digambarkan mengenai apa matahari yang kita kenal dengan "sundayana," lalu "Suryana." Di dalam kala idealnya, mereka menamai hari matahari atau dikenal dengan matahari itu "San" dan hari itu "day." Hari matahari atau Surya ada yang mengenalnya juga "San" atau "Sin" atau "than" atau "ingsun." Di kita ini ada juga yang "sanggup" atau "sound," begitu ya. Atau perubahan istilah itu yang berkaitan dengan Sunda. Sebetulnya sekilas gambaran tadi boleh jadi hanya bersifat "gathuk," katanya kata orang Indonesia yang mencocokkan gitu. Namun, mustahil jika kemiripan penanda sebutan dan objek itu terjadi dengan sendirinya tanpa sebab. Selain itu, terjadi pula kemiripan pada nilai-nilai yang bersifat prinsip. Jadi, pada saat kita menstigma kan tentang cocokologi tadi, harusnya fair juga kalau kita mendengarkan istilah "herdis" dalam bahasa Inggris. Itu asal kata "Ferdy," situ dari "Firdaus." Katanya ini er tatali bahasa tuh.',
        link: 'https://www.youtube.com/watch?v=4Q2qrZMzPdI',
        image: 'images/sundanologi.PNG',
      ),
      Materi(
        judul: 'BELAJAR AKSARA SUNDA DENGAN MUDAH',
        deskripsi1:
            'Aksara Sunda saat ini diajarkan di sekolah. Kebanyakan dari siswa biasanya ingin belajar aksara Sunda dengan mudah. Video ini merupakan pembelajaran aksara Sunda yang dikemas agar mudah dipahami oleh berbagai kalangan, termasuk siswa SD, SMP, SMA, atau umum. Pembelajaran ini tidak hanya mencakup cara menulis aksara Sunda, tetapi juga menjelaskan makna dan sejarah di balik setiap huruf. Dengan pendekatan yang interaktif dan menarik, diharapkan siswa dapat lebih cepat memahami dan menguasai aksara ini.',
        deskripsi2:
            'Selain itu, metode pengajaran yang digunakan dalam video ini mencakup latihan-latihan praktis yang dapat diikuti oleh para siswa. Dengan memberikan contoh-contoh nyata dan aplikasi aksara Sunda dalam kehidupan sehari-hari, siswa diharapkan dapat melihat relevansi dan pentingnya mempelajari aksara ini. Misalnya, mereka dapat belajar menulis nama mereka atau membuat kalimat sederhana dalam aksara Sunda. Hal ini akan meningkatkan minat dan motivasi siswa untuk terus belajar.',
        deskripsi3:
            'Video pembelajaran ini juga dilengkapi dengan visual yang menarik dan penjelasan yang jelas. Dengan menggunakan animasi dan grafik yang menarik, siswa akan lebih terlibat dan tidak merasa bosan saat belajar. Selain itu, penyampaian materi yang sederhana dan lugas akan membantu siswa dari berbagai usia untuk memahami konsep-konsep dasar aksara Sunda dengan lebih baik. Dengan cara ini, diharapkan pembelajaran aksara Sunda menjadi lebih menyenangkan dan tidak menakutkan bagi siswa.',
        deskripsi4:
            'Dengan adanya inisiatif seperti ini, diharapkan aksara Sunda dapat terus dilestarikan dan diperkenalkan kepada generasi muda. Melalui pembelajaran yang menyenangkan dan mudah diakses, siswa tidak hanya akan belajar tentang aksara Sunda, tetapi juga akan menghargai warisan budaya yang ada. Dengan demikian, mereka akan menjadi generasi yang lebih sadar akan pentingnya melestarikan dan meneruskan budaya lokal, termasuk aksara Sunda, kepada generasi berikutnya.',
        link: 'https://www.youtube.com/watch?v=0f9LolhrhYs&t=166s',
        image: 'images/belajar_aksara.PNG',
      ),
      Materi(
        judul:
            'BELAJAR MENULIS AKSARA SUNDA || TRIK CEPAT HAFAL DENGAN RUMUS RAHASIA (HURUF VOKAL) PART 1',
        deskripsi1:
            'Assalamualaikum warahmatullahi wabarakatuh. Halo sobat Almoera! Kembali lagi bersama saya di Aura Channel. Langsung saja, dalam pembelajaran ini, saya akan membagi menjadi lima tahap. Yang pertama, mempelajari huruf vokal. Tahap yang kedua adalah mempelajari huruf konsonan. Tahap yang ketiga mempelajari tanda vokalisasi dalam aksara Sunda. Tahap yang keempat adalah latihan menulis, dan tahap yang kelima adalah latihan membaca. Masing-masing tahap itu ada dalam video yang berbeda. Jadi, di video kali ini, kita hanya akan mempelajari huruf vokalnya dulu secara rinci, secara jelas, dan menggunakan trik-trik ciptaan saya sendiri.',
        deskripsi2:
            'Oh ya, bagi sobat pemula atau yang belum paham banget tentang bahasa Sunda, perlu diketahui bahwa huruf vokal dalam bahasa Sunda itu ada beberapa. Coba ada tuh, cukup! Kalau dalam bahasa Indonesia kan cuma a, i, u, e, o. Itu ada tambahan selain yang a, i, u, e, o, ada juga yang e dan o. Jadi ini ya, a, i, u, e, o, dan u. Huruf vokal dalam bahasa Indonesia kalau di dalam bahasa Sunda ada yang namanya "hai". Habis itu, ada huruf dan itu dibacanya bukan "eh", tapi kalau dalam bahasa Sunda, yang ini jadi "jadi". Soalnya, ini masih banyak orang, teman saya sendiri, yang masih kebingungan dengan perbedaan ini. Nah, ini akan saya jelaskan juga di video yang lain ya, video khusus.',
        deskripsi3:
            'Oke, dari ke-7 huruf vokal ini, kita akan mulai menulis. Sebenarnya, bagaimana sih? Tapi kita harus menggunakan trik yang pertama agar semakin cepat dalam menguasai atau dalam menghafalkan. Oke, aksara Sunda ini banyak banget mirip-mirip ya antara huruf yang satu dengan huruf yang lain. Oleh karena itu, saya menyusunnya menggunakan patokan-patokan khusus agar semakin memudahkan kita dalam mengingat dan menghafalkannya. Jadi, di sini kita tidak menggunakan urutan a, i, u, e, o, untuk mulai menghafalkan, tetapi saya akan menggunakan urutan ini. Yang pertama yang harus dihafal atau dilatih diingat-ingat itu huruf begini nih.',
        deskripsi4:
            'Nah, maaf ya kalau agak jelek karena nulis ini, spidol agak susah juga sih. Maksudnya, ini huruf A itu ada patokannya biar kita mudah mengingat. Karena metode saja sendiri, kalau dalam mempelajari sesuatu atau mengingat sesuatu, menghafal sesuatu, itu harus ada patokan. Baik itu menghafal ayat-ayat Al-Quran atau menghafal rumus-rumus matematika dan lain-lainnya, itu harus ada patokan biar kita semakin mudah mempelajari dan mengingatnya. Untuk huruf A sendiri, saya menggunakan patokannya adalah angka 3. ',
        link: 'https://www.youtube.com/watch?v=eK-S2bNnOfs&t=15s',
        image: 'images/almura.PNG',
      ),
      Materi(
        judul:
            'BELAJAR MENULIS AKSARA SUNDA || TRIK CEPAT HAFAL DENGAN RUMUS RAHASIA (HURUF KONSONAN) PART 2',
        deskripsi1:
            'Assalamualaikum warahmatullahi wabarakatuh. Halo sobat Almoera! Kembali lagi bersama saya di Alam Rencana. Nah, saya sekarang akan melanjutkan video pembelajaran aksara Sunda part 2-nya dan akan membahas tentang huruf konsonan. Sebelum itu, jangan lupa sobat Almoera untuk menekan tombol subscribe agar tidak ketinggalan info-info pembelajaran lainnya di channel ini. Oke, langsung saja ya!. Yang perlu sobat ketahui tentang huruf konsonan dalam aksara Sunda, atau yang disebut aksara Ngalagena, ini sudah otomatis seperti ini. Nah, Kak terasa sakit, jadi bukan huruf advertise of puppets, bukan seperti itu. Tapi memang sudah termasuk huruf A. Nanti untuk bagaimana vokal ini bisa berubah jadi I, U, dan sebagainya, itu nanti akan dijelaskan di part ketiga tentang tanda vokalisasi. Oke, sekarang membahas dulu bahwa huruf konsonan aksara Sunda ini saya sudah membagi-bagi menjadi beberapa kelompok untuk memudahkan dalam proses menghafal serta membedakan. Karena dalam aksara Sunda ini banyak sekali aksara-aksara yang mirip.',
        deskripsi2:
            'Di kelompok pertama, itu ada kelompok angka 7. Jatuh aksara yang memang patoknya ke angka 7 atau mirip dengan ketujuh. Contohnya, yang pertama itu ada huruf K. Penulisannya adalah memang seperti angka 7 biasa, yaitu dua kali Kak Tini. Kemudian huruf R, huruf R itu masuk juga ke ketujuh. Ini untuk roof rack, cara penulisannya seperti itu. Topi kemudian ak71 selalu seperti ada gadis yang mencekik. Aturannya bahwa garis yang atas, yang topi ini, harus sejajar. Jangan seperti ini, ini panjang soalnya. Nah, jangan seperti ini, tapi memang harus sejajar.',
        deskripsi3:
            'Huruf yang ketiga yang mematok juga ke angka 7 adalah T. Ini selesai menulis di papan tulis, pulsa itu angka 7. Angka 7 lalu diberi garis tengahnya sama seperti huruf K. Coba perbedaannya, garis di tengahnya saja. Dan ingat kembali bahwa garis yang di tengah dengan garis yang atasnya atau kepalanya itu harus sama atau sejajar. Kemudian yang terakhir ada huruf X. Atau saat tahu gimana ya nyebutnya, itu adalah kemiripan dari huruf T. Perbedaannya, itu huruf X ini digabung total. Nah, jadi digabung ya. Kalau huruf J, itu kan misah ada celah. Kalau huruf X, itu digabung.',
        deskripsi4:
            'Tipsnya adalah sobat untuk bisa membedakan harus menulis latihan terus. Misalnya satu halaman, kemudian per baris, yaitu harus berbeda-beda urutan. Besarnya baris pertama urutannya seperti ini, kemudian penulisan baris keduanya itu misalnya R dulu, baru snare drum, ska rusak, juga baris ketiga, dan seterusnya. Oke, lanjut kepada kelompok 2. Kelompok 2 ini adalah kelompok Marga Tepuk. Mengapa saya menyebutnya Marga Tepuk? Karena memang bentuknya itu seperti magnetuk atau seperti huruf U.',
        link: 'https://www.youtube.com/watch?v=8DTp-xXIIKo',
        image: 'images/almura2.PNG',
      ),
      Materi(
        judul:
            'AKSARA SUNDA (BAGIAN 2) || MENGENAL DAN LATIHAN MENULIS AKSARA SUNDA [LENGKAP]',
        deskripsi1:
            'Assalamualaikum warahmatullahi wabarakatuh. Sampurasun! Bertemu lagi dengan saya, Aldi Erdiansyah, di channel Racana KW. Pada kesempatan kali ini, saya akan membahas dan melanjutkan materi tentang aksara Sunda. Namun sebelumnya, izinkan saya menggunakan bahasa Indonesia supaya orang-orang yang kurang mengerti bahasa Sunda bisa mengikuti. Karena ini kan materi aksara Sunda, jadi siapa tahu ada orang yang di luar Sunda tapi tertarik untuk mengerti bagaimana sih cara menulis aksara Sunda. Bagaimana sih sistem atau kaidah-kaidah atau aturan-aturan yang harus dilaksanakan ketika kita menulis aksara Sunda.',
        deskripsi2:
            'Oke, sebelum kita memulai, alangkah baiknya kita mengingat kembali ya di video sebelumnya. Bagi yang belum nonton, di video sebelumnya tentang materi aksara Sunda yang bagian teorinya saja, silakan bisa tonton link-nya dari atas. Aksara Sunda, aksara no mimiti dipakai ke urang Sunda, nyaéta aksara Pallawa. Karena aksara Sunda kursi dipakai sejak abad ke-14, jadi aksara Sunda itu pernah dipakai semenjak abad ke-14. Nah, aksara Sunda ke Asep bangun aksara silabis, artinya 21 huruf itu adalah satu suku kata. Itulah aksara silabis.',
        deskripsi3:
            'B dengan aksara fonemis lebih lengkapnya lagi, silakan tonton video saya sebelumnya tentang materi aksara Sunda bagian teorinya. Yuk, sekarang kita mulai! Oke, aksara Sunda baku. Kenapa pembahasan tentang aksara Sunda baku? Karena memang yang menjadi standar aksara Sunda yang diajarkan di tingkat SMP, atau pun SMA, ataupun SD sekalipun, itu aksara Sunda baku. Jadi, teman-teman, aksara Sunda itu sebenarnya banyak. Mulai dari aksara Sunda abad awal-awalnya, abad ke-13 sampai abad ke-20, itu banyak. Mulai dari aksara Pallawa sampai Cacarakan, sampai sekarang, asal sudah baku sebanyak. Tapi yang diajarkan di sekolah-sekolah yaitu aksara Sunda baku yang menjadi standarisasi pendidikan bahasa Sunda di Jawa Barat.',
        deskripsi4:
            'Oke, aksara Sunda itu dibagi menjadi 4 bagian. Yang pertama, suara; yang kedua, Ngalagena; yang ketiga, Rarangken; yang keempat, angka. Nah, apa saja sih arti dari empat jenis aksara Sunda ini? Yang pertama, aksara Swara. Aksara Swara itu adalah aksara vokal. Saya sering menyebutnya aksara vokal mandiri. Vokalisasi di dalam bahasa Sunda itu beda dengan vokalisasi di bahasa Indonesia. Di bahasa Indonesia ada 5 huruf: a, e, i, o, u; sedangkan di aksara Sunda ini ada tujuh: a, e, i, o, u, é, dan é. Nah, suara ini biasanya digunakan sebagai vokal mandiri atau vokal yang tidak ada keterikatan dengan huruf konsonan.',
        link: 'https://www.youtube.com/watch?v=e7UMHDjtnpg',
        image: 'images/angracana.PNG',
      ),
      Materi(
        judul:
            'Aksara Sunda (Aksara Swara, Ngalagena, Rarangken, Jeung Angka)|| Kaidah Nulis Aksara Sunda',
        deskripsi1:
            'Assalamualaikum warahmatullahi taala wabarakatuh. Sampurasun! Alhamdulillah, kita masih bertemu di Desa Ketapang. Dalam pembelajaran Basa Sunda, masih bersama ibu Riswahyuni. Dinamakan Rino Endah, yaitu materinya aksara Sunda. Aksara Sunda teh sapatos kumaha huruf Natal nu kumaha wae. Kumaha carana nulisna? Yuk, kita sasarengan dalam video pembelajaran ini, Sang kandidat biasa mengajarkan nulis aksara Sunda luyu saran kaidah-kaidahna. Mangga, Wilujeng! Ini lowongan di tanah Yoona, tidak kedah uninga bahwa karena kompetensi dasar, IPK sarung tujuanmu baris di hotel disapa. Rantosna, hidup diajar benar aksara Sunda nu kahiji dituntut sudah dia.',
        deskripsi2:
            'Analisis bentuk sarang tipe aksara Sunda luyu dengan kaidah-kaidahnya. Kalian tieta tidak di akhir kedah tiasa nulis nama hidup sawang-sawang, dan menggunakan aksara Sunda. Lajeng, kedah tia sangat transliterasi kecap atau kalimah tina aksara latin. Karena aksara Sunda atau sebaliknya, ajeng nur komunitas tidak sekedar. Dia sangat kreasikan aksara Sunda dina wangun kaligrafi.',
        deskripsi3:
            'Akan tetapi, tujuan ilke nah kontolkuli detik saparantos. Nah, diajar dinten ayeuna salah sangka didepanku. Ngonoo, kangkung, apa lu? Kumaha aksara Sunda teh? Ayeuna urang diajar sasarannya aksara Sunda baku. Nah, abutai aksara Sunda baku dan aksara Sunda teh Ruby-Ruby. Nya, abad-abad kepengker, orang Sunda teh sono karena aksara. Sangkan aksara Sunda ialah betah dunia pendidikan. Ayah aksara Sunda anu tos dibukukeun, anu tos lostina, standarisasi like diajangkeun ditakol Soepomo. Aksara Sunda baku heartbeat, tapi sopir sebut aksara Sunda kaganga.',
        deskripsi4:
            'Aksara vokal nu ngawengku 7 suara atau rapid 7 vokal. Aya aksara Ngalagena, jumlahnya ayah 18 konsonan asli sarang 7 konsonan dina bahasa serapan. Rajanya rarangken nujum lahna ayat 13. Lajeng, muka-muka saya angka jumlahnya 10. Lukuma hio, 4 jenis aksara Sunda teh. Anda orang gua rasa sarang nu kahiji. Bina aksara Sunda teh, nyaeta ayah aksara Swara, yang atanapi aksi vokal. Bianto Isna ayah huruf a, i, u, e, o, sareng nah ya y.',
        link: 'https://www.youtube.com/watch?v=uwMZoxT7Z3M',
        image: 'images/lies.PNG',
      ),

      // Tambahkan materi lainnya sesuai kebutuhan
    ];
  }
}
